# ?? ? DBMS ?? ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers


#JPA ?? ?? ??
  jpa:
    show-sql: true    # ????? ???? sql? ??
    database: mysql   # ??? ???? DBMS ??
    hibernate:
      ddl-auto: create
      # create : ?????? ?? ? ?? ??? ?? ? ?? ??? entity???? ??
      # none : DB ??? ???? ??, ?? DB ??
      # update : ??? ?????? ???? ???? ?? ???? -> ?? DB? ???? ?? ?? ?? ????
      # create-drop : ???? ????? ?? ??? drop ???.

    properties:
      hibernate:
        format_sql: true    # SQL? ???? ? ???? ?? ??

